name: ltp_env

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.9
  - pip
  - numpy
  - pandas
  - seaborn
  - pytorch
  - torchvision
  - torchaudio
  - tensorflow==2.11.*

  - pip:
    - transformers
    - evaluate
    - datasets
    - keras==2.11
    - tf-keras
    - protobuf==3.20.3
    - sentencepiece
    - nltk
    - rouge_score
    - abs
    - language_tool_python
    - sentence_transformers
    - torch
    - peft
    - optuna
    - matplotlib
    - typing-extensions
    - concurrent
    - pathlib
    - json
    - sys
    - logging
