name: ltp_env

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.8
  - pip
  - pip:
      - evaluate
      - sentence-transformers
      - torch
      - matplotlib
      - numpy
      - seaborn
      - pandas
      - optuna
      - datasets
      - transformers
      - peft
      - language_tool_python
      - nltk
